type ContractAuthority =
  | "public"
  | "bootstrap-token"
  | "authenticated-principal"
  | "administrator"
  | "session-or-library"
  | "session-or-playback"
  | "session-or-user-state"
  | "plugin-bearer";

export const contractAuthorityByMethod = {
  "nama.api.v1.AuthService.ApproveDeviceAuthorization": "authenticated-principal",
  "nama.api.v1.AuthService.GetCurrentUser": "administrator",
  "nama.api.v1.AuthService.RevokeAppleClientRefreshTokens": "administrator",
  "nama.api.v1.AuthService.SignIn": "public",
  "nama.api.v1.AuthService.SignOut": "administrator",
  "nama.api.v1.HealthService.Check": "administrator",
  "nama.api.v1.HealthService.GetDiagnostics": "administrator",
  "nama.api.v1.LibraryService.GetHome": "session-or-library",
  "nama.api.v1.LibraryService.GetMedia": "session-or-library",
  "nama.api.v1.LibraryService.GetMediaSource": "session-or-library",
  "nama.api.v1.LibraryService.ListChildren": "session-or-library",
  "nama.api.v1.LibraryService.ListLibrary": "session-or-library",
  "nama.api.v1.LibraryService.ResolveArtwork": "session-or-library",
  "nama.api.v1.LibraryService.Search": "session-or-library",
  "nama.api.v1.PlaybackService.ClosePlayback": "session-or-playback",
  "nama.api.v1.PlaybackService.OpenPlayback": "session-or-playback",
  "nama.api.v1.PlaybackService.PlanPlayback": "session-or-playback",
  "nama.api.v1.PlaybackService.ReportPlayback": "session-or-playback",
  "nama.api.v1.ProviderService.CreateProviderInstance": "administrator",
  "nama.api.v1.ProviderService.DeleteProviderInstance": "administrator",
  "nama.api.v1.ProviderService.GetProviderInstance": "administrator",
  "nama.api.v1.ProviderService.ListProviderInstances": "administrator",
  "nama.api.v1.ProviderService.ListProviderTypes": "administrator",
  "nama.api.v1.ProviderService.TestProviderConfiguration": "administrator",
  "nama.api.v1.ProviderService.TestProviderInstance": "administrator",
  "nama.api.v1.ProviderService.UpdateProviderInstance": "administrator",
  "nama.api.v1.SetupService.CreateAdministrator": "bootstrap-token",
  "nama.api.v1.SetupService.GetStatus": "public",
  "nama.api.v1.SyncService.GetSyncRun": "administrator",
  "nama.api.v1.SyncService.GetSyncStatus": "administrator",
  "nama.api.v1.SyncService.TriggerSync": "administrator",
  "nama.api.v1.UserStateService.GetUserState": "session-or-user-state",
  "nama.api.v1.UserStateService.SetWatched": "session-or-user-state",
  "nama.plugin.v1.HealthService.Check": "plugin-bearer",
  "nama.plugin.v1.LibraryService.GetItem": "plugin-bearer",
  "nama.plugin.v1.LibraryService.ListItems": "plugin-bearer",
  "nama.plugin.v1.LibraryService.ResolveArtwork": "plugin-bearer",
  "nama.plugin.v1.PlaybackService.ClosePlayback": "plugin-bearer",
  "nama.plugin.v1.PlaybackService.OpenPlayback": "plugin-bearer",
  "nama.plugin.v1.PlaybackService.PlanPlayback": "plugin-bearer",
  "nama.plugin.v1.PlaybackService.ReportPlayback": "plugin-bearer",
  "nama.plugin.v1.PluginService.GetConnection": "plugin-bearer",
  "nama.plugin.v1.PluginService.GetInfo": "plugin-bearer",
  "nama.plugin.v1.WatchStateService.GetWatchStates": "plugin-bearer",
  "nama.plugin.v1.WatchStateService.ListWatchStates": "plugin-bearer",
  "nama.plugin.v1.WatchStateService.PushWatchStates": "plugin-bearer",
} as const satisfies Record<string, ContractAuthority>;
