const CONTRACT_MAJOR = 1;
const ENVELOPE_VERSION = 1;
const HANDSHAKE_TIMEOUT_MILLISECONDS = 5000;
const CONNECT_TIMEOUT_SLACK_MILLISECONDS = 100;
const LAUNCH_PROTOCOL_REJECTION_EXIT_CODE = 64;
const MAXIMUM_ENVELOPE_BYTES = 4096;
const MAXIMUM_SOCKET_PATH_BYTES = 100;
const PROCESS_TERMINATION_TIMEOUT_MILLISECONDS = 2000;
const INITIAL_RECOVERY_DELAY_MILLISECONDS = 0;
const FIRST_RECOVERY_DELAY_MILLISECONDS = 100;
const SECOND_RECOVERY_DELAY_MILLISECONDS = 500;
const RECOVERY_DELAYS_MILLISECONDS = [
  INITIAL_RECOVERY_DELAY_MILLISECONDS,
  FIRST_RECOVERY_DELAY_MILLISECONDS,
  SECOND_RECOVERY_DELAY_MILLISECONDS,
] as const;
const HEALTHY_EPISODE_RESET_MILLISECONDS = 60_000;
const RPC_TIMEOUT_RECOVERY_GRACE_MILLISECONDS = 1000;
const SOCKET_FILENAME = "p.sock";
const DIRECTORY_MODE = 0o700;
const SOCKET_MODE = 0o600;
const SOCKET_MODE_MASK = 0o777;
const UNSAFE_EXECUTABLE_MODE = 0o022;
const PLUGIN_BEARER_BYTES = 32;
const SOCKET_POLL_MILLISECONDS = 5;
const SAFE_PLUGIN_IDENTIFIER = /^[a-z][a-z0-9._-]{0,127}$/u;
const SAFE_PLUGIN_ENUM_VALUE = /^[A-Za-z0-9._:-]{1,64}$/u;
const RESERVED_PLUGIN_LOG_FIELDS: Readonly<Record<string, true>> = Object.freeze({
  connect_code: true,
  duration_ms: true,
  error_tag: true,
  event: true,
  exit_code: true,
  level: true,
  provider_instance_id: true,
  provider_type: true,
  recovery_attempt: true,
  request_id: true,
  rpc_method: true,
  sanitized_stack_frames: true,
  signal: true,
  timestamp: true,
});

export {
  CONNECT_TIMEOUT_SLACK_MILLISECONDS,
  CONTRACT_MAJOR,
  DIRECTORY_MODE,
  ENVELOPE_VERSION,
  HANDSHAKE_TIMEOUT_MILLISECONDS,
  HEALTHY_EPISODE_RESET_MILLISECONDS,
  LAUNCH_PROTOCOL_REJECTION_EXIT_CODE,
  MAXIMUM_ENVELOPE_BYTES,
  MAXIMUM_SOCKET_PATH_BYTES,
  PLUGIN_BEARER_BYTES,
  PROCESS_TERMINATION_TIMEOUT_MILLISECONDS,
  RECOVERY_DELAYS_MILLISECONDS,
  RESERVED_PLUGIN_LOG_FIELDS,
  RPC_TIMEOUT_RECOVERY_GRACE_MILLISECONDS,
  SAFE_PLUGIN_ENUM_VALUE,
  SAFE_PLUGIN_IDENTIFIER,
  SOCKET_FILENAME,
  SOCKET_MODE,
  SOCKET_MODE_MASK,
  SOCKET_POLL_MILLISECONDS,
  UNSAFE_EXECUTABLE_MODE,
};
